# Problem set 1

## Q1: Tensors and Automatic Differentiation


### Q1a

In [1]:
import torch
import numpy as np

torch.manual_seed(42)

if torch.cuda.is_available():
    DEVICE = torch.device("cuda")
else:
    DEVICE = torch.device("cpu")

In [ ]:
#Q1a.1
a = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32).to(DEVICE)

#Q1a.2
ones = np.ones((3,3))
b = torch.tensor(ones, dtype=torch.float32).to(DEVICE)

In [ ]:
#Q1a.3
a_transpose = a.unsqueeze(1)

#Q1a.4
square = torch.square(a)
square

tensor([ 1.,  4.,  9., 16., 25.])

In [9]:
#Q1a.5
b_b = b@b

b_b

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

### Q1b

$f(x) = x^2 + 3x + 1$ 

$df/dx = 2x + 3$

When $x = 2, df/dx = 7$

In [12]:
x = torch.tensor([2],dtype=torch.float32,  requires_grad=True)
y = x **2 + 3*x + 1
y.backward()
print(x.grad)

tensor([7.])
